### ISSUE TITLE
Support less strict parsing of semi-colons

### ISSUE THREAD

**Issue by bartkl** [quoll/raphael#4]
Hey Paula,

As discussed briefly on Slack, many tools generate Turtle code that contains trailing semi-colons like so:

```turtle
[
  sh:path ex:name ;
  sh:datatype xsd:int ;  # <- removing this semi-colon fixes the parsing error
]
```

This example also doesn't work, although I'm not sure if the proposed leniency should stretch so far as to support this as well:

```turtle
shape:idShape
    a sh:PropertyShape ;
    sh:path vocab:id ;
    sh:datatype xsd:string ;
    sh:minCount 1 ;  # <-- removing this semi-colon fixes the parsing error
.
```

So I'm not sure about the exact scope of how lenient one should want to be and when, i.e. if there's other cases like this where semi-colons or dots trail where it would be pragmatic to accept them. I'm sure you'll know where to look seeing how familiar you are with the grammar :).

It would be nice if Raphael could deal with letting that strict incorrectness slide, so it becomes compatible with potentially many tools.

Thanks!

**Comment by quoll** [comment]
I can add this, but I plan to log the error. Maybe I should provide an option to keep that quiet

**Comment by bartkl** [comment]
Yeah it makes sense to let people know that this is tolerated, but not formally correct.

Being able to supress the error (warning?) would improve the UX I think.

**Comment by quoll** [comment]
I still need to add logging, but semi-colons are now allowed to terminate predicate-object lists.

After putting out v0.1.1 I realized that I could also do the same for object lists (meaning that they could end in illegal comma characters) so I added this as well. It's all in v0.1.2
